"""File-based imports and cached finders used by different ThreadGroups."""

import textwrap
import unittest

from test.support import threading_helper
from test.support.script_helper import assert_python_ok


threading_helper.requires_working_threading(module=True)


class FileImportAccessTests(unittest.TestCase):
    PRELUDE = '''
import os
import sys
import tempfile
import threading
from test.support import threading_helper
from importlib.machinery import FileFinder, PathFinder, SourceFileLoader

results = threading.Channel()
errors = SynchronizedList()

def run(*actions):
    def worker(action):
        try:
            action()
        except BaseException as exc:
            frames = []
            tb = exc.__traceback__
            while tb is not None:
                frames.append((tb.tb_frame.f_code.co_name, tb.tb_lineno))
                tb = tb.tb_next
            errors.append((type(exc).__name__, str(exc), tuple(frames)))
    threads = [threading.Thread(target=worker, args=(action,),
                                group=threading.ThreadGroup())
               for action in actions]
    with threading_helper.start_threads(threads):
        pass
    assert not errors, list(errors)

def write(directory, name, source):
    path = os.path.join(directory, name)
    with open(path, 'w', encoding='utf-8') as file:
        file.write(source)
    return path
'''

    def run_script(self, script):
        assert_python_ok('-c', self.PRELUDE + textwrap.dedent(script))

    def test_source_import_with_main_cached_finder(self):
        self.check_source_import(warm_cache=True)

    def test_source_import_with_new_finder(self):
        self.check_source_import(warm_cache=False)

    def check_source_import(self, *, warm_cache):
        self.run_script(f'''
            warm_cache = {warm_cache!r}
            with tempfile.TemporaryDirectory() as directory:
                write(directory, 'pep805_source.py',
                      'answer = 42\\ndef calculate(): return answer + 1\\n')
                if warm_cache:
                    spec = PathFinder.find_spec('pep805_source', [directory])
                    finder = sys.path_importer_cache[directory]
                    assert type(finder) is FileFinder
                sys.path.insert(0, directory)
                def action():
                    import pep805_source
                    assert pep805_source.calculate() == 43
                    assert pep805_source.__shareable__ is threading.Shareable.LOCAL
                    assert __import__('pep805_source') is pep805_source
                    results.put(pep805_source.__spec__.cached)
                run(action)
                assert os.path.isfile(results.get())
                try:
                    sys.modules['pep805_source']
                except IllegalThreadAccessException:
                    pass
                else:
                    raise AssertionError('worker module implicitly shared')
                # A new group now reads the generated bytecode through the
                # same finder, without acquiring the first group's module.
                del sys.modules['pep805_source']
                run(action)
                assert os.path.isfile(results.get())
        ''')

    def test_file_finder_concurrent_refresh(self):
        self.run_script('''
            with tempfile.TemporaryDirectory() as directory:
                write(directory, 'pep805_cached.py', 'answer = 42\\n')
                finder = FileFinder(directory, (SourceFileLoader, ('.py',)))
                def action():
                    for _ in range(20):
                        finder.invalidate_caches()
                        spec = finder.find_spec('pep805_cached')
                        assert spec is not None
                        assert spec.name == 'pep805_cached'
                        assert spec.loader.__shareable__ is threading.Shareable.LOCAL
                    results.put('found')
                run(action, action, action, action)
                assert [results.get() for _ in range(4)] == ['found'] * 4
                assert finder.__shareable__ is threading.Shareable.SYNCHRONIZED
        ''')

    def test_package_and_namespace_package_in_worker(self):
        self.run_script('''
            for regular in (True, False):
                with tempfile.TemporaryDirectory() as directory:
                    name = 'pep805_package' if regular else 'pep805_namespace'
                    package = os.path.join(directory, name)
                    os.mkdir(package)
                    if regular:
                        write(package, '__init__.py', 'initialized = True\\n')
                    write(package, 'child.py', 'answer = 42\\n')
                    sys.path.insert(0, directory)
                    def action():
                        child = __import__(name + '.child', fromlist=('answer',))
                        assert child.answer == 42
                        assert child.__shareable__ is threading.Shareable.LOCAL
                        parent = sys.modules[name]
                        assert parent.__shareable__ is threading.Shareable.LOCAL
                        if regular:
                            assert parent.initialized
                    run(action)
                    sys.path.remove(directory)
        ''')

    def test_file_finder_subclass_stays_local(self):
        self.run_script('''
            class CustomFinder(FileFinder):
                pass
            with tempfile.TemporaryDirectory() as directory:
                finder = CustomFinder(directory, (SourceFileLoader, ('.py',)))
                assert finder.__shareable__ is threading.Shareable.LOCAL
                def action():
                    try:
                        finder.find_spec('pep805_missing')
                    except IllegalThreadAccessException:
                        results.put('denied')
                    else:
                        raise AssertionError('finder subclass implicitly shared')
                run(action)
                assert results.get() == 'denied'
        ''')

    def test_foreign_loader_rejected(self):
        self.run_script('''
            calls = []
            class Loader:
                def __init__(self, *args):
                    calls.append(args)
            with tempfile.TemporaryDirectory() as directory:
                write(directory, 'pep805_local_loader.py', 'answer = 42\\n')
                finder = FileFinder(directory, (Loader, ('.py',)))
                def action():
                    try:
                        finder.find_spec('pep805_local_loader')
                    except IllegalThreadAccessException:
                        results.put('denied')
                    else:
                        raise AssertionError('foreign loader called')
                run(action)
                assert results.get() == 'denied'
                assert calls == []
        ''')

    def test_shared_code_filename_update(self):
        self.run_script('''
            import _imp
            code = compile('def inner(): return 42', 'old-path', 'exec')
            class LocalFilename(str):
                pass
            inaccessible = code.replace(co_filename=LocalFilename('foreign'))
            def action():
                _imp._fix_co_filename(code, 'new-path')
                assert code.co_filename == 'new-path'
                assert code.co_consts[0].co_filename == 'new-path'
                try:
                    _imp._fix_co_filename(inaccessible, 'forbidden')
                except IllegalThreadAccessException:
                    pass
                else:
                    raise AssertionError('foreign filename metadata acquired')
            run(action)
            assert inaccessible.co_filename == 'foreign'
        ''')

    def test_filesystem_error_types_in_worker(self):
        self.run_script('''
            import _io
            from errno import ENOENT, EEXIST
            from os import stat
            with tempfile.TemporaryDirectory() as directory:
                missing = os.path.join(directory, 'missing')
                def action():
                    assert type(OSError(ENOENT, 'missing')) is FileNotFoundError
                    assert type(OSError(EEXIST, 'exists')) is FileExistsError
                    for read in (lambda: stat(missing),
                                 lambda: _io.open_code(missing)):
                        try:
                            read()
                        except FileNotFoundError as exc:
                            assert exc.errno == ENOENT
                            assert exc.filename == missing
                        else:
                            raise AssertionError('missing file opened')
                run(action)
        ''')

    def test_native_import_with_inherited_globals(self):
        self.run_script('''
            import _testlimitedcapi
            import _testinternalcapi
            native_import = _testlimitedcapi.PyImport_Import
            _testinternalcapi.object_declare_synchronized(native_import)
            namespace = {
                '__builtins__': {'__import__': __import__},
                'native_import': native_import,
            }
            exec('def invoke(): return native_import("sys")', namespace)
            invoke = namespace['invoke']
            def action():
                assert invoke() is sys
            run(action)
        ''')

    def test_native_import_checks_hooks_and_exposed_globals(self):
        self.run_script('''
            import _testlimitedcapi
            import _testinternalcapi
            native_import = _testlimitedcapi.PyImport_Import
            _testinternalcapi.object_declare_synchronized(native_import)
            calls = threading.Channel()
            class LocalHook:
                def __call__(self, *args):
                    calls.put('local hook called')
                    return sys
            def shared_hook(*args):
                calls.put('shared hook called')
                return sys
            for hook in (LocalHook(), shared_hook):
                namespace = {
                    '__builtins__': {'__import__': hook},
                    'native_import': native_import,
                }
                exec('def invoke(): return native_import("sys")', namespace)
                invoke = namespace['invoke']
                def action():
                    try:
                        invoke()
                    except IllegalThreadAccessException:
                        results.put('denied')
                    else:
                        raise AssertionError('foreign hook or globals exposed')
                run(action)
                assert results.get() == 'denied'
            try:
                calls.get()
            except IndexError:
                pass
            else:
                raise AssertionError('import hook called without access')
        ''')


if __name__ == '__main__':
    unittest.main()
