name: Manual Windows

on:
  workflow_dispatch:
    inputs:
      arch:
        description: CPU architecture
        required: true
        type: choice
        options:
          - x86
          - x64
          - arm64
      free-threading:
        description: Whether to compile CPython in free-threading mode
        required: false
        type: boolean
        default: false

env:
  FORCE_COLOR: 1

jobs:
  build-windows:
    uses: ./.github/workflows/reusable-windows.yml
    with:
      arch: ${{ inputs.arch }}
      free-threading: ${{ inputs.free-threading }}
